[server]
# Streamlit should always run in headless mode on hosted environments so
# the CLI does not block waiting for interactive prompts (for example the
# welcome email capture).  Running headless also mirrors how developers run
# `streamlit run` locally.
headless = true
# remove enableCORS; Streamlit will set it safely with XSRF on

[browser]
# Disable usage stats prompts so Streamlit will not pause waiting for input
# in non-interactive CI/container environments.
gatherUsageStats = false

[theme]
primaryColor="#0b5cd8"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f6f8fa"
textColor="#111418"
